In [1]:
df=pd.read_csv("../DATA/customer.csv")

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OrdinalEncoder
df=pd.read_csv("../DATA/customer.csv")
df.head()
df = df.iloc[:,2:]

In [19]:
# df = df.drop(columns=['age'], axis=1)

In [20]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [26]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2, random_state=42)

In [27]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((40, 2), (10, 2), (40,), (10,))

In [28]:
X_train.head()

     review education
12     Poor    School
4   Average        UG
37  Average        PG
8   Average        UG
3      Good        PG

In [31]:
# Create an OrdinalEncoder instance
from pyparsing import col
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

# Fit the encoder to the training data
encoder.fit(X_train)

# Transform the training and testing data
X_train_encoded = encoder.transform(X_train)
X_test_encoded = encoder.transform(X_test)

# Print the transformed data
print(X_train_encoded)

[[0. 0.]
 [1. 1.]
 [1. 2.]
 [1. 1.]
 [2. 2.]
 [2. 0.]
 [2. 2.]
 [0. 2.]
 [2. 2.]
 [0. 1.]
 [2. 1.]
 [0. 1.]
 [1. 2.]
 [1. 0.]
 [0. 0.]
 [1. 0.]
 [1. 1.]
 [0. 2.]
 [2. 2.]
 [1. 0.]
 [1. 1.]
 [2. 1.]
 [2. 1.]
 [0. 1.]
 [1. 2.]
 [2. 2.]
 [0. 2.]
 [0. 0.]
 [2. 0.]
 [2. 0.]
 [2. 1.]
 [0. 2.]
 [2. 0.]
 [2. 1.]
 [1. 0.]
 [0. 0.]
 [2. 2.]
 [0. 2.]
 [0. 0.]
 [2. 0.]]

In [32]:
encoder.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [33]:
## for the output column we use the label encoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [34]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [35]:
y_test

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1])

In [36]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No