In [1]:
from sklearn.ensemble import BaggingClassifier
from sklearn.datasets import load_iris

In [2]:
df  = load_iris()

In [3]:
X,y = df.data , df.target

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
df = pd.DataFrame(X,columns =df.feature_names )

In [6]:
df["target"] = y

In [7]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [8]:
X = df.iloc[:,:4]
X
y = df.iloc[:,-1]
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [10]:
bg = BaggingClassifier(estimator=DecisionTreeClassifier(),  n_estimators=100, max_samples=50,max_features=2, bootstrap=True)

In [11]:
bg.fit(X_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), max_features=2,
                  max_samples=50, n_estimators=100)

In [12]:
ypred = bg.predict(X_test)

In [36]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
accuracy_score(ypred,y_test)

0.9666666666666667

In [76]:
param_grid = {
    'estimator': [DecisionTreeClassifier(), SVC(), LogisticRegression(), KNeighborsClassifier()],
    'n_estimators': [100, 200],  # Number of base learners
    'max_samples': [0.1, 0.2, 0.4, 0.5, 0.7],  # Proportion of training data per estimator
    'max_features': [0.1, 0.2, 0.4, 0.5, 0.7],  # Proportion of features per estimator
    'bootstrap': [True, False],  # Sampling with/without replacement
    'bootstrap_features': [True, False]  # Sampling features with/without replacement
}


from sklearn.model_selection import GridSearchCV
bgclf = BaggingClassifier(random_state=42)
gd = GridSearchCV(bgclf, param_grid,cv=5,n_jobs=-1)

In [77]:

gd.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=BaggingClassifier(random_state=42), n_jobs=-1,
             param_grid={'bootstrap': [True, False],
                         'bootstrap_features': [True, False],
                         'estimator': [DecisionTreeClassifier(), SVC(),
                                       LogisticRegression(),
                                       KNeighborsClassifier()],
                         'max_features': [0.1, 0.2, 0.4, 0.5, 0.7],
                         'max_samples': [0.1, 0.2, 0.4, 0.5, 0.7],
                         'n_estimators': [100, 200]})

In [78]:
gd.best_params_

{'bootstrap': False,
 'bootstrap_features': True,
 'estimator': SVC(),
 'max_features': 0.1,
 'max_samples': 0.1,
 'n_estimators': 200}

In [79]:
gd.best_score_

0.9583333333333334

In [80]:
best_model = gd.best_estimator_
best_model.score(X_test,y_test)

0.9333333333333333

In [81]:
gd.best_estimator_

BaggingClassifier(bootstrap=False, bootstrap_features=True, estimator=SVC(),
                  max_features=0.1, max_samples=0.1, n_estimators=200,
                  random_state=42)

In [82]:
import pandas as pd

# Convert GridSearchCV results to a DataFrame
results = pd.DataFrame(gd.cv_results_)

# Select relevant columns (Base Estimator & Performance)
results = results.sort_values(by='mean_test_score', ascending=False)
# results[0]['params']
results[['params']]

                                                params
471  {'bootstrap': False, 'bootstrap_features': Tru...
451  {'bootstrap': False, 'bootstrap_features': Tru...
482  {'bootstrap': False, 'bootstrap_features': Tru...
461  {'bootstrap': False, 'bootstrap_features': Tru...
492  {'bootstrap': False, 'bootstrap_features': Tru...
..                                                 ...
301  {'bootstrap': True, 'bootstrap_features': Fals...
311  {'bootstrap': True, 'bootstrap_features': Fals...
320  {'bootstrap': True, 'bootstrap_features': Fals...
310  {'bootstrap': True, 'bootstrap_features': Fals...
300  {'bootstrap': True, 'bootstrap_features': Fals...

[800 rows x 1 columns]

In [ ]:
gd.cv_results_

{'mean_fit_time': array([0.53510103, 1.11842895, 1.50596833, 0.59144521, 1.09304152,
        1.53862705, 0.61894612, 1.0712718 , 1.46867919, 0.49104209,
        1.00135136, 1.4244236 , 0.50340371, 1.0075067 , 1.45777607,
        0.48490906, 0.97914228, 1.4558166 , 0.50179701, 0.96939306,
        1.46608062, 0.48735404, 1.01615996, 1.49218864, 0.49247079,
        0.98465133, 1.44338923, 0.49459176, 1.0087306 , 1.43814259,
        0.49499173, 0.98484898, 1.43498902, 0.49291368, 0.99091296,
        1.45591745, 0.48322029, 0.98818364, 1.4161159 , 0.50586195,
        0.98619347, 1.45911131, 0.48049245, 0.99045095, 1.49597816,
        0.50118985, 0.95506101, 1.4812809 , 0.49247637, 0.95515213,
        1.4677844 , 0.50508866, 0.97075405, 1.45409455, 0.49733238,
        0.99134312, 1.47727599, 0.49248338, 0.9940402 , 1.44945183,
        0.49862986, 0.96971869, 1.48170156, 0.48307762, 0.95489712,
        1.48574901, 0.48142209, 0.96131129, 1.49980607, 0.48465457,
        0.9628037 , 1.48993697, 0.49419379, 0.97758527, 1.47931786,
        0.48981705, 0.9736352 , 1.42476397, 0.49354835, 1.00904927,
        1.43472853, 0.49755616, 0.99106979, 1.46719675, 0.49740529,
        0.97818618, 1.47776952, 0.47774782, 0.9959116 , 1.4489789 ,
        0.47884116, 1.01224732, 1.50132914, 0.56678495, 0.99974198,
        1.47197981, 0.49439325, 0.99405012, 1.45451794, 0.50716772,
        0.97599497, 1.47966909, 0.48706775, 0.97295012, 1.47537813,
        0.48637938, 0.97531652, 1.4456018 , 0.49372621, 0.96627798,
        1.46980476, 0.48019691, 0.97264571, 1.46137676, 0.50249548,
        1.01407461, 1.43604021, 0.49694462, 0.99645181, 1.46178603,
        0.47667432, 0.98102517, 1.43408995, 0.49984088, 0.9920537 ,
        1.45206623, 0.52952361, 1.00316529, 1.47828536, 0.48848925,
        0.97006607, 1.50052123, 0.49438157, 0.96360826, 1.51290636,
        0.47623768, 1.01310496, 1.4847621 , 0.48362927, 0.97084651,
        1.47605448, 0.49715323, 1.01496782, 1.41549869, 0.49606185,
        1.00973101, 1.43110175, 0.50695229, 1.01068296, 1.48520646,
        0.47758012, 0.9698844 , 1.61748462, 0.54162169, 1.06142244,
        1.55184603, 0.50882101, 0.99948707, 1.45491586, 0.51971593,
        1.03252916, 1.46423635, 0.51626492, 1.0624269 , 1.44282846,
        0.51450715, 1.00436153, 1.48755708, 0.493785  , 0.97469754,
        1.51649284, 0.48533316, 0.9616178 , 1.50417023, 0.49272599,
        0.97270994, 1.49304852, 0.51300054, 1.01856995, 1.47480803,
        0.50017066, 0.97293773, 1.49158068, 0.50904069, 0.99637899,
        1.51401491, 0.49948997, 0.9811264 , 1.57095156, 0.50663614,
        0.98365068, 1.4884851 , 0.50769362, 1.01709743, 1.48274999,
        0.51283927, 1.06518998, 1.46557775, 0.49868717, 1.02516847,
        1.44011416, 0.51619864, 1.03967376, 1.51653619, 0.5298017 ,
        1.06215329, 1.71013527, 0.49760432, 1.15415654, 1.61044946,
        0.50360646, 1.01692691, 1.49718351, 0.50899048, 0.99652953,
        1.51730561, 0.49516864, 1.00395641, 1.52258968, 0.51413665,
        1.01365061, 1.51506419, 0.5018826 , 1.01763992, 1.53359041,
        0.50267711, 0.9933115 , 1.47432113, 0.51388221, 1.0143187 ,
        1.486941  , 0.50478072, 1.00611696, 1.47333918, 0.50489049,
        1.02844586, 1.48207717, 0.50237122, 0.98448601, 1.53869233,
        0.48751349, 0.98643847, 1.45343738, 0.50693345, 1.00347991,
        1.44673004, 0.50869946, 0.99290495, 1.4879447 , 0.50672407,
        1.01307864, 1.5144196 , 0.51671877, 0.9945807 , 1.48306003,
        0.49068561, 1.00660458, 1.47594647, 0.49848647, 1.00460968,
        1.48439589, 0.50907831, 0.99671359, 1.47557311, 0.5087069 ,
        1.03234057, 1.46030655, 0.50288768, 1.06066685, 1.53694119,
        0.54015398, 1.02721171, 1.52458582, 0.49626703, 1.03941569,
        1.47229075, 0.51556315, 1.02306437, 1.47256312, 0.50172343,
        1.00240192, 1.50413408, 0.52923765, 1.06110587, 1.66933184,
        0.63157616, 1.1425509 , 1.67175531, 0.59305172, 1.00138078,
        1.49746027, 0.48328047, 0.96078601, 1.48684464, 0.49227376,
        0.97187853, 1.61605501, 0.50026159, 1.10497699, 1.32932434]),
 'std_fit_time': array([0.03642183, 0.10391608, 0.14195734, 0.08067971, 0.08219504,
        0.09518715, 0.0728279 , 0.0707862 , 0.07289668, 0.0119865 ,
        0.05160348, 0.06262473, 0.01038131, 0.0354286 , 0.05988289,
        0.02758854, 0.03779934, 0.04690484, 0.03053263, 0.05034509,
        0.07175863, 0.02098815, 0.04141435, 0.06036062, 0.01997475,
        0.02992417, 0.06833046, 0.02166554, 0.02174514, 0.05415439,
        0.01853418, 0.04259342, 0.07202632, 0.02508123, 0.03934554,
        0.06978058, 0.01457895, 0.038736  , 0.04673851, 0.01609802,
        0.05671626, 0.06557298, 0.01956133, 0.04990837, 0.05723229,
        0.0368078 , 0.04470016, 0.06020244, 0.02928091, 0.04244357,
        0.0454884 , 0.0324145 , 0.04066935, 0.06898515, 0.01649408,
        0.0457399 , 0.06441949, 0.02149355, 0.04805868, 0.05331982,
        0.02146301, 0.04857443, 0.05849508, 0.01562537, 0.04443659,
        0.04964477, 0.02250375, 0.04479725, 0.06135662, 0.02212197,
        0.04704973, 0.05355232, 0.02344143, 0.04170308, 0.08563564,
        0.01156959, 0.04540192, 0.05695508, 0.02480218, 0.02128403,
        0.04797352, 0.02599419, 0.04137164, 0.0688089 , 0.0147302 ,
        0.0457622 , 0.07164602, 0.02111328, 0.04033691, 0.05252565,
        0.0218998 , 0.07307724, 0.09240902, 0.05198633, 0.05416758,
        0.06208795, 0.02305029, 0.02752002, 0.060197  , 0.02586432,
        0.049444  , 0.05214669, 0.02369839, 0.06089574, 0.06971768,
        0.01858788, 0.04276608, 0.0429577 , 0.02815478, 0.0441938 ,
        0.03768592, 0.02870775, 0.0349013 , 0.06917995, 0.02047108,
        0.05201699, 0.05215864, 0.02251167, 0.04494322, 0.06404224,
        0.02013403, 0.03472778, 0.06928955, 0.00554018, 0.03802363,
        0.04500399, 0.02477682, 0.04918499, 0.03810259, 0.03400363,
        0.04131317, 0.05968574, 0.01775061, 0.06384377, 0.06658321,
        0.02997137, 0.05335369, 0.08410888, 0.02077786, 0.03320821,
        0.0440893 , 0.03402295, 0.0401289 , 0.0443073 , 0.01799944,
        0.04814781, 0.05281994, 0.00633718, 0.0481144 , 0.03743683,
        0.03012098, 0.05580501, 0.09009888, 0.07429932, 0.09463617,
        0.06278337, 0.04296029, 0.04331876, 0.05802897, 0.01735736,
        0.04279739, 0.07992451, 0.01931223, 0.0593103 , 0.03851176,
        0.02591156, 0.0269987 , 0.0601747 , 0.02435016, 0.05662276,
        0.02886232, 0.02470851, 0.04810914, 0.07861969, 0.02959238,
        0.02722379, 0.06951672, 0.0114996 , 0.05342006, 0.0516477 ,
        0.02235957, 0.03662666, 0.06986302, 0.02722512, 0.06700408,
        0.05962125, 0.0303737 , 0.05587946, 0.04038395, 0.02890302,
        0.04204186, 0.08247625, 0.03055292, 0.02452087, 0.11013612,
        0.01434323, 0.04660838, 0.09731109, 0.01000702, 0.01769066,
        0.06591425, 0.02512451, 0.0579538 , 0.06459822, 0.04143171,
        0.05788324, 0.13843391, 0.02023694, 0.05698225, 0.07954691,
        0.00775666, 0.03241539, 0.05552807, 0.01879635, 0.03122979,
        0.05754143, 0.02441439, 0.04133146, 0.07000089, 0.02135583,
        0.04398   , 0.07159342, 0.01498429, 0.02275146, 0.08360767,
        0.02407964, 0.01067906, 0.0847578 , 0.03241598, 0.03696297,
        0.04694343, 0.00953165, 0.04655341, 0.05094358, 0.01235981,
        0.02507015, 0.05597889, 0.02317611, 0.03450776, 0.06340237,
        0.01379986, 0.01586652, 0.07694679, 0.01615916, 0.0353648 ,
        0.0450699 , 0.02765584, 0.02771049, 0.05816717, 0.02865029,
        0.04037967, 0.07147188, 0.02728134, 0.04074832, 0.04103458,
        0.02483065, 0.04480826, 0.05063915, 0.02387542, 0.03245132,
        0.07197177, 0.02018116, 0.01667124, 0.0570799 , 0.02154224,
        0.02762552, 0.03328529, 0.01551956, 0.03278133, 0.07576313,
        0.03317508, 0.03177478, 0.08060581, 0.02370778, 0.07304109,
        0.03570255, 0.02337085, 0.04765942, 0.05192973, 0.01358185,
        0.03958283, 0.04946688, 0.02045762, 0.0432876 , 0.15125005,
        0.15239957, 0.13572972, 0.2119052 , 0.05701645, 0.02682215,
        0.05537946, 0.02305436, 0.05277771, 0.06019693, 0.02778788,
        0.04668044, 0.09972833, 0.02875539, 0.11645094, 0.05088896]),
 'mean_score_time': array([0.03613067, 0.07755289, 0.10274916, 0.03679113, 0.06885304,
        0.09096122, 0.04640064, 0.06541343, 0.09299598, 0.03318682,
        0.06382122, 0.09225931, 0.03610234, 0.06251349, 0.0981976 ,
        0.0340548 , 0.06088524, 0.09358406, 0.03411198, 0.06192908,
        0.09575586, 0.0336463 , 0.0605587 , 0.0929451 , 0.03491297,
        0.06404805, 0.08974271, 0.03268566, 0.07001071, 0.09179564,
        0.03470373, 0.06603727, 0.09461274, 0.03270187, 0.06446691,
        0.0940392 , 0.03537817, 0.06248589, 0.09196734, 0.03330107,
        0.06468363, 0.09321527, 0.03270016, 0.06640534, 0.09555635,
        0.03316336, 0.06257501, 0.09261746, 0.03292689, 0.06012855,
        0.09573674, 0.03574991, 0.06312366, 0.09124994, 0.03903518,
        0.06543179, 0.09117699, 0.03420658, 0.06365805, 0.09112391,
        0.03462071, 0.06523509, 0.09169936, 0.03311958, 0.06567955,
        0.09637747, 0.03284898, 0.06330724, 0.09097366, 0.03499966,
        0.06165352, 0.09546108, 0.03457727, 0.06196871, 0.09168482,
        0.03311162, 0.06553707, 0.0898159 , 0.03227224, 0.07043099,
        0.09167562, 0.03344197, 0.06248317, 0.08992515, 0.03384314,
        0.06418414, 0.09142351, 0.03477263, 0.06596146, 0.09028521,
        0.03543215, 0.08394308, 0.09188399, 0.03533745, 0.0651268 ,
        0.09326248, 0.03306088, 0.06231747, 0.09326982, 0.03439393,
        0.06629181, 0.09321456, 0.03274598, 0.06310978, 0.09297624,
        0.03314538, 0.0637466 , 0.08932428, 0.03502026, 0.06440096,
        0.09609194, 0.03242393, 0.06246819, 0.0936233 , 0.03602982,
        0.0621129 , 0.09063935, 0.03412881, 0.06318998, 0.09557519,
        0.03460231, 0.06406884, 0.09039216, 0.03604355, 0.06909842,
        0.0883512 , 0.03475676, 0.0629487 , 0.09127336, 0.03352213,
        0.06096749, 0.0926363 , 0.03397098, 0.06142569, 0.094484  ,
        0.03326235, 0.06684413, 0.09657445, 0.03670034, 0.06216564,
        0.09273505, 0.03436747, 0.06901002, 0.09034243, 0.03709226,
        0.06541438, 0.08847065, 0.0328712 , 0.06527023, 0.09856987,
        0.03125281, 0.06224384, 0.10039945, 0.03906221, 0.06282248,
        0.08935356, 0.0340229 , 0.06111221, 0.09425344, 0.03410587,
        0.0689476 , 0.09049311, 0.03431621, 0.06400585, 0.09089823,
        0.03799133, 0.06294484, 0.09240856, 0.03445339, 0.06261549,
        0.09601603, 0.03464446, 0.06000404, 0.09653044, 0.03631067,
        0.06060648, 0.09693546, 0.03285427, 0.0635499 , 0.09244294,
        0.03377447, 0.06256571, 0.09489017, 0.03283687, 0.06245203,
        0.09969106, 0.03425899, 0.06767955, 0.09430523, 0.03143191,
        0.06362901, 0.09364305, 0.03290782, 0.0668355 , 0.10392437,
        0.03514037, 0.06555028, 0.09015694, 0.03492947, 0.07062316,
        0.09084535, 0.03412399, 0.07084012, 0.09755716, 0.03828712,
        0.06448073, 0.11872091, 0.03648844, 0.06688299, 0.0973732 ,
        0.03771896, 0.06537957, 0.09371433, 0.03444157, 0.0639503 ,
        0.09400387, 0.03332033, 0.06235371, 0.09465232, 0.03283873,
        0.06531444, 0.0983252 , 0.0339622 , 0.06314235, 0.0963232 ,
        0.03569593, 0.0646297 , 0.09383855, 0.03325725, 0.06777244,
        0.09413295, 0.03251534, 0.06235924, 0.09251981, 0.03393559,
        0.06671886, 0.09409494, 0.03278742, 0.0612689 , 0.09909678,
        0.03324366, 0.06806731, 0.09388652, 0.03412757, 0.06585574,
        0.09301257, 0.03538337, 0.06202855, 0.09260559, 0.03324475,
        0.06670074, 0.0959878 , 0.03312726, 0.0636035 , 0.09548645,
        0.03544083, 0.06322803, 0.09577961, 0.03266897, 0.06341653,
        0.0981607 , 0.0337656 , 0.0625093 , 0.09518785, 0.03577256,
        0.06699896, 0.09312491, 0.03410258, 0.07415032, 0.0960278 ,
        0.03845205, 0.06745033, 0.1038703 , 0.03555541, 0.06577792,
        0.09122005, 0.0328845 , 0.06696448, 0.09441085, 0.03529954,
        0.06663313, 0.0935111 , 0.03401289, 0.07367964, 0.09036646,
        0.04057302, 0.10055199, 0.09529958, 0.04305029, 0.06644602,
        0.09602699, 0.03339477, 0.06423674, 0.0954318 , 0.03405247,
        0.06268778, 0.10857706, 0.03377709, 0.05979061, 0.06885133]),
 'std_score_time': array([0.0069148 , 0.01286682, 0.01970698, 0.00420038, 0.00394116,
        0.00409784, 0.01397688, 0.0068461 , 0.0058735 , 0.00242203,
        0.00400138, 0.00607915, 0.0043481 , 0.00396964, 0.00633376,
        0.0033856 , 0.00241305, 0.0053284 , 0.00271226, 0.00154334,
        0.006367  , 0.00292586, 0.00274572, 0.0062916 , 0.00135878,
        0.00251698, 0.0064253 , 0.00205965, 0.00589241, 0.0075633 ,
        0.00265575, 0.00495842, 0.01036557, 0.00175136, 0.00225124,
        0.00570148, 0.0015487 , 0.00297106, 0.00490995, 0.00239215,
        0.00389873, 0.00613274, 0.00153162, 0.01193478, 0.00464203,
        0.00230253, 0.00117178, 0.00585111, 0.00181221, 0.00162421,
        0.0075457 , 0.00159333, 0.00275845, 0.0062822 , 0.0119797 ,
        0.00335385, 0.00502309, 0.00400994, 0.00214056, 0.00330831,
        0.00307222, 0.00595998, 0.00337145, 0.00160727, 0.00295307,
        0.00693563, 0.0015579 , 0.00421659, 0.00543689, 0.0044793 ,
        0.00451688, 0.00575318, 0.00195899, 0.00312459, 0.00653188,
        0.00169247, 0.00436284, 0.00432646, 0.00374992, 0.00408   ,
        0.0044911 , 0.00289692, 0.00495111, 0.00103544, 0.00183712,
        0.00786551, 0.00510633, 0.0037461 , 0.00470153, 0.00363592,
        0.0022621 , 0.03826918, 0.00645144, 0.0032841 , 0.00244033,
        0.0060172 , 0.00202555, 0.00317656, 0.0065043 , 0.00217606,
        0.00418699, 0.00448482, 0.00192594, 0.00288524, 0.00809714,
        0.00138158, 0.00175717, 0.00266461, 0.00427198, 0.00387259,
        0.00620135, 0.00293237, 0.00286698, 0.00587164, 0.00341477,
        0.00458117, 0.0032788 , 0.0015939 , 0.00371794, 0.00564111,
        0.00278665, 0.00808866, 0.00479615, 0.00142148, 0.01337804,
        0.00244943, 0.00265526, 0.00279743, 0.00446335, 0.00185112,
        0.00404435, 0.00620817, 0.00234571, 0.00431551, 0.00534444,
        0.00356791, 0.00701654, 0.00671802, 0.0036946 , 0.00372238,
        0.0041954 , 0.00301255, 0.00728095, 0.00397473, 0.00615297,
        0.00232076, 0.0053827 , 0.00309188, 0.00555659, 0.00939661,
        0.00086472, 0.00557689, 0.01150365, 0.00772297, 0.00246232,
        0.00448102, 0.00356946, 0.00437511, 0.00538936, 0.00092795,
        0.00565122, 0.0035911 , 0.00224973, 0.00294533, 0.0042718 ,
        0.00594081, 0.00548698, 0.00474242, 0.00312418, 0.0039404 ,
        0.00557429, 0.0041952 , 0.00168151, 0.00549967, 0.00504573,
        0.00229989, 0.00453702, 0.00124716, 0.00361334, 0.00556621,
        0.00199689, 0.00466019, 0.00719564, 0.00134287, 0.00213635,
        0.01715783, 0.00472271, 0.01127604, 0.00322635, 0.00075782,
        0.00300579, 0.00837922, 0.00306324, 0.00243812, 0.01347642,
        0.00244509, 0.00449638, 0.00493359, 0.00230091, 0.00653123,
        0.00487895, 0.0024678 , 0.00734484, 0.01594229, 0.0058502 ,
        0.0045969 , 0.03092772, 0.00511845, 0.00587684, 0.00685449,
        0.00254602, 0.00327566, 0.00464727, 0.00275575, 0.00392154,
        0.00569401, 0.0030007 , 0.00206331, 0.00483561, 0.00166723,
        0.00239921, 0.00478496, 0.00144176, 0.00374532, 0.00950321,
        0.00160547, 0.00235973, 0.00651246, 0.00144503, 0.00274975,
        0.00372164, 0.00170052, 0.00275499, 0.00634707, 0.00245903,
        0.00197711, 0.00756709, 0.0011384 , 0.00456713, 0.00789869,
        0.00258056, 0.00137535, 0.00259428, 0.00128362, 0.00353023,
        0.0074638 , 0.0006213 , 0.00229055, 0.00463986, 0.00208655,
        0.00826874, 0.00822082, 0.0009106 , 0.00311023, 0.00260809,
        0.00465704, 0.00446441, 0.0051314 , 0.00170715, 0.00423379,
        0.00678471, 0.00125286, 0.00271141, 0.01181442, 0.00249645,
        0.00646759, 0.0020831 , 0.0030202 , 0.0094708 , 0.00317885,
        0.00735253, 0.00496297, 0.00833885, 0.00433374, 0.00371321,
        0.00504955, 0.00212806, 0.00257021, 0.00118058, 0.00189312,
        0.0063222 , 0.00491816, 0.00216393, 0.01108222, 0.00533924,
        0.00465711, 0.05595783, 0.0064091 , 0.01448395, 0.00372328,
        0.00582113, 0.00223027, 0.00550865, 0.00651466, 0.00181282,
        0.00526535, 0.0189937 , 0.00238369, 0.00648939, 0.00314115]),
 'param_bootstrap': masked_array(data=[True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,

In [83]:
print("Best Base Estimator:", gd.best_params_)

Best Base Estimator: {'bootstrap': False, 'bootstrap_features': True, 'estimator': SVC(), 'max_features': 0.1, 'max_samples': 0.1, 'n_estimators': 200}